# Generated by Django 4.2.26 on 2025-11-22 02:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ram', models.CharField(max_length=20, verbose_name='Memoria RAM')),
                ('almacenamiento', models.CharField(max_length=20, verbose_name='Almacenamiento Interno')),
                ('camara', models.CharField(max_length=50, verbose_name='Cámara Principal')),
                ('bateria', models.CharField(max_length=50, verbose_name='Batería')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='celulares/')),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=2, verbose_name='Alerta Stock Mínimo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('cliente_telefono', models.CharField(max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_reserva', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Retiro'), ('ENTREGADO', 'Entregado / Venta Finalizada'), ('CANCELADO', 'Cancelado / No recogido')], default='PENDIENTE', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('celular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.celular')),
            ],
        ),
        migrations.AddField(
            model_name='celular',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.marca'),
        ),
    ]
